language: minimal
dist: xenial
sudo: false

script: ./travis.script.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: war
    target_branch: gh-pages
    on:
      branch: master
  - provider: releases
    api-key:
      # encrypted github oauth token
      # travis encrypt "github oath token goes in these quotes" --add deploy.api-key -r gchq/stroom-visualisations-dev
      secure: bh04l/7WruYQ2dKaSjubHJsmMdRCgsoX7cM0XznSc0BLAepvwv4h/uCQKT1T6cIXo8pr3EtzXpHghfd+vqlBSAG25cuURFT7S62CdqQdTG6SLsaBTnnpXRqL8YKYr0jlTVmZy+eA3QT5+lrWzQVYMVk+MHSDZkRb1d3lakSqJez2zFrv7cBM9qTTWQXM5qKmyAACxi/x8TBIfYhOgLfmpgcDb/oAfwMgpYr4c8t6H1TWqDqGMFQ8tZdVnXIt841dnKSWEapq6phUeRZfhQ2LZoYO6Pz16AsjyaaHoPNtrs+usnxoCxM2TueYxJC4jpkkxVmU1e7qhTsZLS42IGl53eM7rOWpp6ijtfherP6f6sw0qUcFwqnOAHAXIBjqm3cAYxUpZGiOiSAIzykOsAJzNlxjiaPR8DqrNvcSFHrm0Ud3HCo1qx39aXN1HG4VIOwdgajIZVvI19fg9vhnRVvDI5uIfPcyfRHvFT1dMq/Y8qWoZryLP5283WQOKom7dKgw8E7FJYx0CisK8uFHTj34WHCOlJmTF8OvxWTAtXqsUAEKSPy8N5V5utXhd4sdlvqG1rL3dsBjkYepYNSJE+xELyPyhlkP+Jma7DWvi1rG5g8w3h/Gw8j+lh//HPqKrQ3PKqNAGm3NdrQHC/sPJiWYymhAgdXZBtNWPj/r9U8Fq2M=
    file_glob: true
    # Pick up all .zip and .zip.sha256 files
    file: "./stroom-content-artifacts/*.zip*"
    skip_cleanup: true
    on:
      tags: true
