language: minimal
dist: xenial
sudo: false

script: ./travis.script.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: war
    target_branch: gh-pages
    on:
      branch: master
  - provider: releases
    api-key:
      # encrypted github oauth token
      # travis encrypt "github oath token goes in these quotes" --add deploy.api-key -r gchq/stroom-visualisations-dev
      secure: qGZbhFQQEmpudGUbDBSy/iBp8xg4NllawLsLYkpwTuoTVIqosVwc/+6fCgN0HgMwrsmUWY0VRtbs78OX9wzeLPrhrzA4E6vO4eAOWuZlqsZ3tgFrCkVH40EEL0eiGtOyuJT6YUUKJAs7leYO7ZLR6of9uu+XWwSBSCN1YSllp+V9+R05kuE4sVXHgLy/ZMgeQ8fr0gLCQMBTIQoepIOiPgx356ET0NRPyRe6xTriBVVUnkEQAplPAC0C89PGKoSN0rpj2Yi5p8JoLtVGVYES7wireGMJBC9/P8Ovx4Hehs+Ax9MVtX4NsOqEaHwR8jftogeMikdwDaR4UbUrdp13PI5Fqs5Ks4qummd0tklk9+SG1pgdehNVEjha0ycnEe1z2y/Kyb5COI4795koy0+D4HxQ8xHHElHWnwHNqngOLCaYVxXmccTl+da/4/H5TulKxR2BnivRKOEEqKJ6x8a7XiqtJDpI8FA+GpXwd5Ii5YOvlf4F23KqKty5JwvIKcyvF8b12jdmuSI3DDAW8+UfjrJt2CMfBFmlkldyUK/CnwI1XB4fn3kv6lcgFKXenu8Pli+Ffa7ifU1pe+O+P9yo1yYnxb9F5uRyA/QpVCUgAGW3RW8d7pM2Z4+ybwCvk8mH7TbFR9QkKBAT0JJ77/Bu18871JhGao9KTqXO2pjQtAY=
    file_glob: true
    # Pick up all .zip and .zip.sha256 files
    file: "./stroom-content-artifacts/*.zip*"
    skip_cleanup: true
    on:
      tags: true




