name: Zip files on push

on:
  push:
  pull_request:

jobs:
  build-project:
    runs-on: ubuntu-20.04  
    env:                   
      MAX_WORKERS: 3
      SSH_AUTH_SOCK: "/tmp/ssh-agent.sock"
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        id: checkout_code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variables
        id: set_env_var
        run: |
          {
            # Map the GITHUB env vars to our own
            echo "BUILD_DIR=${GITHUB_WORKSPACE}"
            echo "BUILD_COMMIT=${GITHUB_SHA}"
            echo "ACTIONS_SCRIPTS_DIR=${GITHUB_WORKSPACE}/.github/workflows/scripts"

            if [[ ${GITHUB_REF} =~ ^refs/tags/ ]]; then
              # strip off the 'refs/tags/' bit
              tag="${GITHUB_REF#refs/tags/}"
              echo "BUILD_TAG=${tag}"
            fi

            if [[ ${GITHUB_REF} =~ ^refs/heads/ ]]; then
              # strip off the 'ref/heads/' bit
              echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}"
            fi

            if [[ ${GITHUB_REF} =~ ^refs/pulls/ ]]; then
              echo "BUILD_IS_PULL_REQUEST=true"
            else
              echo "BUILD_IS_PULL_REQUEST=false"
            fi

            if [[ ${GITHUB_REF} =~ ^refs/tags/v ]]; then
              echo "BUILD_IS_RELEASE=true"
            else
              echo "BUILD_IS_RELEASE=false"
            fi
          } >> $GITHUB_ENV

      - name: Build Environment Info
        id: build_info
        run: |
          "${ACTIONS_SCRIPTS_DIR}/create_github_release.sh" \
            "docker version" "$(docker --version)" \
            "docker compose version" "$(docker compose version)" \
            "git version" "$(git --version)" \
            "GITHUB_WORKSPACE" "$GITHUB_WORKSPACE" \
            "GITHUB_REF" "$GITHUB_REF" \
            "GITHUB_SHA" "$GITHUB_SHA" \
            "BUILD_DIR" "$BUILD_DIR" \
            "BUILD_TAG" "$BUILD_TAG" \
            "BUILD_BRANCH" "$BUILD_BRANCH" \
            "BUILD_COMMIT" "$BUILD_COMMIT" \
            "BUILD_IS_PULL_REQUEST" "$BUILD_IS_PULL_REQUEST" \
            "BUILD_IS_RELEASE" "$BUILD_IS_RELEASE" \
            "ACTIONS_SCRIPTS_DIR" "$ACTIONS_SCRIPTS_DIR" \
            "PWD" "$PWD" \
            "HOME" "$HOME"

      - name: Create Tag if Not Exists
        if: env.tag_exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$tag_name" -m "Auto-created tag $tag_name"
          git push origin "$tag_name"

      - name: Zip
        run: |
          mkdir -p "${BUILD_DIR}/build/release_artefacts/"
          mkdir -p "test_dir"
          zip -r "${BUILD_DIR}/build/release_artefacts/stroom-content.zip" "./war/stroom-content"
          zip -r "test_dir/stroom-content.zip" "./war/stroom-content"

      - name: Release to Github
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash "${ACTIONS_SCRIPTS_DIR}/create_github_release.sh"
