name: zip files on push

on:
  push:
  pull_request:

jobs:
  build-project:
    runs on: ubuntu-20.4
    env: 
      MAX_WORKERS: 3


  steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with: ref: ${{ github.ref }}

    - name: Set Environment
      id: set_environment
      run: |
        {
          # Map the GITHUB env vars to our own
          echo "BUILD_DIR=${GITHUB_WORKSPACE}"
          echo "BUILD_COMMIT=${GITHUB_SHA}"
          echo "ACTIONS_SCRIPTS_DIR=${GITHUB_WORKSPACE}/.github/workflows/scripts"

          if [[ ${GITHUB_REF} =~ ^refs/tags/ ]]; then
            # strip off the 'refs/tags/' bit
            tag="${GITHUB_REF#refs/tags/}"
            echo "BUILD_TAG=${tag}"
          fi

          if [[ ${GITHUB_REF} =~ ^refs/heads/ ]]; then
            # strip off the 'ref/heads/' bit
            echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}"
          fi

          if [[ ${GITHUB_REF} =~ ^refs/pulls/ ]]; then
            echo "BUILD_IS_PULL_REQUEST=true"
          else
            echo "BUILD_IS_PULL_REQUEST=false"
          fi

          if [[ ${GITHUB_REF} =~ ^refs/tags/v ]]; then
            echo "BUILD_IS_RELEASE=true"
          else
            echo "BUILD_IS_RELEASE=false"
          fi
        } >> $GITHUB_ENV

    - name: Build Environment
      id: build_environment
      run: |
          "GITHUB_WORKSPACE" "${GITHUB_WORKSPACE}" \
          "BUILD_DIR" "$BUILD_DIR" \

    - name: Zip
      run: | 
        mkdir -p ../build
        zip -r ${BUILD_DIR}/release_artefacts/ ../stroom-content

    - name: Release to Github
      id: create_release
      if: ${{ env.BUILD_IS_RELEASE == 'true' }}
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "${ACTIONS_SCRIPTS_DIR}/create_github_release.sh"
    
